version: 2
jobs:
  build:
    docker:
      - image: elixir:1.4.2

    working_directory: ~/ex_lcd

    environment:
      MIX_ENV: test

    steps:
      - run: mix local.hex --force
      - checkout
      - run: mix deps.get
