version: 2
jobs:
  build:
    docker:
      - image: elixir:1.4.2

    working_directory: ~/ex_lcd

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get

      # Run tests
      - run:
          environment:
            MIX_ENV: test
          command: mix test
