version: 2
jobs:
  build:
    docker:
      - image: cthree87/docker-elixir-ci:latest

    working_directory: ~/ex_lcd

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile

      # Run tests
      - run:
          environment:
            MIX_ENV: "test"
          command: |
            mix test

  deploy_hex:
    docker:
      - image: cthree87/docker-elixir-ci:latest

    working_directory: ~/ex_lcd_deploy

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile

      # Deploy to Hex
      - deploy:
        command: |
          if [ ${CIRCLE_BRANCH} == "master" ]; then
            # Hex authentication expect script
            expect .circleci/hex_auth.expect
            # Publish the new release to hex
            expect .circleci/hex_publish.expect
          fi
